export const ACCESS_TOKEN = 'Access-Token'
export const REFRESH_TOKEN = 'Refresh-Token'
export const TOKEN_EXPIRE_TIME = 'TOKEN_EXPIRE_TIME'
export const TOKEN = 'TOKEN'
export const SIDEBAR_TYPE = 'sidebar_type'
